### ISSUE TITLE
Semester & Campus Agnostic

### ISSUE THREAD

**Issue by aneesh-neelam** [ashwini0529/ffcs-timetable#1]
Make this semester and campus agnostic, with the ability to plan your classes and slots for every semester. 

This ensures that it works for Fall, Intersession, Winter and Summer semesters in both Vellore and Chennai campuses.

**Comment by ashwini0529** [comment]
Sure. Last night I was just designing the front end. Will ensure that it works for all Semesters and for both campuses. :)
It would be great if you contribute in this! :)

**Comment by aneesh-neelam** [comment]
Make it more like an planner for your classes. I suppose that is your aim anyway.

**Comment by ashwini0529** [comment]
Sure. I will focus upon making it a planner for classes. I am making this thing for first year's people so that when they face FFCS, they must have an idea about how things work in VIT.

**Comment by aneesh-neelam** [comment]
Well, that's the point. Making planning and understanding FFCS easier.

**Comment by ashwini0529** [comment]
Exactly! :) I will work upon that and will try my best to make things easier!
