### ISSUE TITLE
Hosted site

### ISSUE THREAD

**Issue by rahulkapoor90** [ashwini0529/ffcs-timetable#3]
where have you planned to host this repository? there are more pull requests coming from me soon.

**Comment by ashwini0529** [comment]
I will host it on a dedicated server. Link to this would be given soon.

**Comment by ghost** [comment]
Use the digital ocean credits you get from github student pack

**Comment by ashwini0529** [comment]
Well I dont owe a student pack!

**Comment by ghost** [comment]
Its free for a student Google it, you should get it in a week or so
